<div align="center">
<img src="https://drive.google.com/uc?id=1JOzNG8Sf9rXQ_nHqlzOvzOnpr4iSIkmc" width="250">

<img src="https://drive.google.com/uc?id=1SctzfeQJDdGN2eMRQhJEoQWWO9rovrWh" width="300">
</div>


## Numpy

[Numpy](https://numpy.org/) is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. To use Numpy, we first need to import the numpy package as `import numpy as np`


In [ ]:
import numpy as np

### Arrays

A numpy array is a grid of values, **all of the same type**, and is indexed by a tuple of nonnegative integers. **The number of dimensions is the rank of the array**; the shape of an array is a tuple of integers giving the size of the array along each dimension. We can initialize numpy arrays from nested Python lists, and access elements using square brackets:


In [ ]:
a = np.array([1, 2, 3])  # Create a rank 1 array
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # Change an element of the array
print(a)

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [ ]:
b = np.array([[1, 2, 3],[4, 5, 6]])   # Create a rank 2 array
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


Numpy also provides many functions to create arrays:


In [ ]:
a = np.zeros((2, 2, 2))  # Create an array of all zeros
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
b = np.ones((1, 2))   # Create an array of all ones
print(b)

[[1. 1.]]


In [ ]:
c = np.full((2,2), 10.0) # Create a constant array
print(c)

[[10. 10.]
 [10. 10.]]


In [ ]:
d = np.eye(2)        # Create a 2x2 identity matrix
print(d)

[[1. 0.]
 [0. 1.]]


In [ ]:
e = np.random.random((2,2))*10 # Create an array filled with random values
print(e)

[[9.82900845 1.16622612]
 [5.26258993 1.3212441 ]]


In [ ]:
# range(1, 11, 2)

ri = np.random.randint(1, 101, (2, 2))
ri

array([[ 5, 98],
       [88, 27]])

In [ ]:
elements = [1, 2, 3, 4, 5]
random_sample = np.random.choice(elements, size=3, replace=False)
random_sample

array([3, 2, 1])

### Datatypes

**Every numpy array is a grid of elements of the same type.** Numpy provides a large set of numeric datatypes that you can use to construct arrays. **Numpy tries to guess a datatype when you create an array**, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

You can read all about numpy datatypes in the [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).


In [ ]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.float32)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

int64 float64 float32


## Array math

**Basic mathematical functions operate elementwise on arrays**, and are available both as operator overloads and as functions in the numpy module:


In [ ]:
x = np.array([[1,2],
              [3,4]]) # 2, 2
y = np.array([[5,6],
              [7,8]]) # 2, 2

# Elementwise sum; both produce the array
print(x + y)

[[ 6  8]
 [10 12]]


In [ ]:
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [ ]:
# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [ ]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [ ]:
print(np.exp(x))

[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]


## **Important Note**

`*` is elementwise multiplication, not matrix multiplication. **We instead use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices.** dot is available both as a function in the numpy module and as an instance method of array objects:


In [ ]:
x = np.array([[1,2],[3,4]]) # 2, 2
y = np.array([[5,6],[7,8]]) # 2, 2

v = np.array([9,10])  # 1, 2
# v = v.reshape(1, len(v))
w = np.array([11, 12]) # 1, 2
# w.reshape(1, len(w))


# Inner product of vectors; both produce 219
print(v.dot(w.transpose()))
# print(np.dot(v, w.transpose()))

219


**You can also use the @ operator which is equivalent to numpy's dot operator.**


In [ ]:
print(v @ w)

219


In [ ]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))
print(x @ v)

[29 67]
[29 67]
[29 67]


In [ ]:
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))
print(x @ y)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:


In [ ]:
x = np.array([[1,2],
              [3,4]])

print(np.sum(x) ) # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


You can find the full list of mathematical functions provided by numpy in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:


In [ ]:
print(x)
print("transpose\n", x.T)

[[1 2]
 [3 4]]
transpose
 [[1 3]
 [2 4]]


In [ ]:
v = np.array([[1,2,3]])
print(v )
print("transpose\n", v.T)

[[1 2 3]]
transpose
 [[1]
 [2]
 [3]]


In [ ]:
import numpy as np

# example of numpy array
x = np.array([1, 2, 3])
print(x)

[1 2 3]


If $x$ is a vector, then a Python operation such as $s = x + 3$ or $s = \frac{1}{x}$ will output s as a vector of the same size as x.


In [ ]:
# example of vector operation
x = np.array([1, 2, 3])
print (x + 3)

[4 5 6]


In fact, if $ x = (x_1, x_2, ..., x_n)$ is a row vector then $np.exp(x)$ will apply the exponential function to every element of x. The output will thus be: $np.exp(x) = (e^{x_1}, e^{x_2}, ..., e^{x_n})$


In [ ]:
import numpy as np

# example of np.exp
x = np.array([1, 2, 3])
print(np.exp(x)) # result is (exp(1), exp(2), exp(3))

[ 2.71828183  7.3890561  20.08553692]


Any time you need more info on a numpy function, we encourage you to look at [the official documentation](https://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.exp.html).


## What is Pytorch?

[PyTorch](https://pytorch.org/) is a python package built by **Facebook AI Research (FAIR)** that provides two high-level features:

- Tensor computation (like numpy) with strong GPU acceleration
- Deep Neural Networks built on a tape-based autograd (_Automatic Gradient Calculation_) system

## Why Pytorch?

- **More Pythonic**

  - Flexible
  - Intuitive and cleaner code
  - Easy to learn & debug
  - Dynamic Computation Graph (_network behavior can be changed programmatically at runtime_)

- **More Neural Networkic**
  - Write code as the network works
  - forward/backward


## Checking PyTorch version


In [ ]:
import torch

print(torch.__version__)

2.3.0


## Introduction to Tensors

A **PyTorch Tensor** is basically the same as a numpy array: it does not know anything about deep learning or computational graphs or gradients, and is just a generic **n-dimensional array** to be used for arbitrary **numeric computation**.

The biggest difference between a numpy array and a PyTorch Tensor is that a **PyTorch Tensor can run on either CPU or GPU**. To run operations on the GPU, **just cast the Tensor to a cuda datatype**.

A scalar is **zero-order tensor** or rank zero tensor. A vector is a **one-dimensional** or first order tensor, and a matrix is a **two-dimensional** or second order tensor.

<div align="center">
<img src="https://drive.google.com/uc?id=1pka-LVyrq_7r0sCm59cvOQofEYAcnO4r" width="550">
</div>

<div align="center">
<img src="https://drive.google.com/uc?id=1zHT5CGzIgpe1aLkdawrllTMn74nYVeAp" width="550">
</div>


A [torch.Tensor](https://pytorch.org/docs/stable/tensors.html) is a **multi-dimensional matrix** containing elements of a **single data type**.

`torch.Tensor` is an alias for the default tensor type (`torch.FloatTensor`).


In [ ]:
torch.tensor([[1, -1],
              [1, -1]])

tensor([[ 1, -1],
        [ 1, -1]])

In [ ]:
x = torch.rand([5, 3])
print(type(x))

<class 'torch.Tensor'>


In [ ]:
torch.randint(1, 101, (2, 2))

tensor([[38, 92],
        [57, 12]])

In [ ]:
torch.ones((2, 2))

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
# Converting numpy arrays to tensors
import numpy as np

np_arr = np.array([[1, 2, 3], [4, 5, 6]])
torch.tensor(np_arr, dtype = torch.int)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [ ]:
# Converting numpy arrays to tensors
np_values = np.array([[1, 2, 3], [4, 5, 6]])

tensor_values = torch.from_numpy(np_values)

print (tensor_values)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
# A tensor of specific data type can be constructed by passing a torch.dtype

torch.zeros([2, 4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# The contents of a tensor can be accessed and modified using Python’s indexing and slicing notation:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x[1, 2])

# Modify a certain element
x[0][1] = 8
print(x)

tensor(6)
tensor([[1, 8, 3],
        [4, 5, 6]])


In [ ]:
# Use torch.Tensor.item() to get a Python number from a tensor containing a single value

x = torch.tensor([[1]])
print(x)
y = x.item()
print(y)

x = torch.tensor(2.5)

print(x.item())

tensor([[1]])
1
2.5


In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x.size())

torch.Size([2, 3])


In [ ]:
# Tensor addition & subtraction
x = torch.rand(5, 3)
y = torch.rand(5, 3)

print(x)
print(y)

print(x + y)
print(x - y)

tensor([[0.0430, 0.9832, 0.6139],
        [0.8795, 0.7155, 0.2965],
        [0.8613, 0.8023, 0.2825],
        [0.7371, 0.3929, 0.1718],
        [0.2717, 0.2105, 0.3344]])
tensor([[0.8813, 0.6820, 0.3434],
        [0.0244, 0.4584, 0.2618],
        [0.5758, 0.1594, 0.9410],
        [0.7899, 0.9223, 0.5685],
        [0.6818, 0.9042, 0.5461]])
tensor([[0.9244, 1.6651, 0.9573],
        [0.9039, 1.1739, 0.5583],
        [1.4372, 0.9617, 1.2236],
        [1.5269, 1.3152, 0.7404],
        [0.9535, 1.1147, 0.8805]])
tensor([[-0.8383,  0.3012,  0.2705],
        [ 0.8550,  0.2571,  0.0346],
        [ 0.2855,  0.6429, -0.6585],
        [-0.0528, -0.5293, -0.3967],
        [-0.4101, -0.6937, -0.2117]])


In [ ]:
# Syntax 2 for Tensor addition & subtraction in PyTorch
print(torch.add(x, y))
print(torch.sub(x, y))
print(x*y)
x.mul(y)

tensor([[0.9244, 1.6651, 0.9573],
        [0.9039, 1.1739, 0.5583],
        [1.4372, 0.9617, 1.2236],
        [1.5269, 1.3152, 0.7404],
        [0.9535, 1.1147, 0.8805]])
tensor([[-0.8383,  0.3012,  0.2705],
        [ 0.8550,  0.2571,  0.0346],
        [ 0.2855,  0.6429, -0.6585],
        [-0.0528, -0.5293, -0.3967],
        [-0.4101, -0.6937, -0.2117]])
tensor([[0.0379, 0.6705, 0.2108],
        [0.0215, 0.3280, 0.0776],
        [0.4960, 0.1279, 0.2659],
        [0.5822, 0.3624, 0.0977],
        [0.1852, 0.1903, 0.1826]])


tensor([[0.0379, 0.6705, 0.2108],
        [0.0215, 0.3280, 0.0776],
        [0.4960, 0.1279, 0.2659],
        [0.5822, 0.3624, 0.0977],
        [0.1852, 0.1903, 0.1826]])

In [ ]:
# Tensor Product & Transpose

mat1 = torch.randn(2, 3)
mat2 = torch.randn(3, 3)

print(mat1)
print(mat2)

print(torch.mm(mat1, mat2))

print(mat1.t())

tensor([[ 1.1977, -1.2243,  0.8041],
        [ 0.9805,  0.0492,  0.8918]])
tensor([[ 0.1874,  0.7875, -1.1915],
        [ 0.4665,  0.4122, -0.2270],
        [ 1.3900, -1.3476,  0.4686]])
tensor([[ 0.7710, -0.6450, -0.7724],
        [ 1.4463, -0.4094, -0.7615]])
tensor([[ 1.1977,  0.9805],
        [-1.2243,  0.0492],
        [ 0.8041,  0.8918]])


In [ ]:
# Elementwise multiplication
t = torch.Tensor([[1, 2], [3, 4]])
t.mul(t)

tensor([[ 1.,  4.],
        [ 9., 16.]])

In [ ]:
# Shape, dimensions, and datatype of a tensor object

x = torch.rand(5, 3)

print('Tensor shape:', x.shape)   # t.size() gives the same
print('Number of dimensions:', x.dim())
print('Tensor type:', x.type())   # there are other types

Tensor shape: torch.Size([5, 3])
Number of dimensions: 2
Tensor type: torch.FloatTensor


In [ ]:
# Slicing
t = torch.Tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9],
                  [7, 8, 9]])

# Every row, only the last column
print(t[-1])

# First 2 rows, all columns
print(t[:2, :])

# Lower right most corner
print(t[-1:, -1:])

tensor([7., 8., 9.])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[9.]])


In [ ]:
t = torch.Tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9],
                  [10, 11, 12]])

t[0:2, 1:3]

tensor([[2., 3.],
        [5., 6.]])

In [ ]:
t[-3:-1, -2:]

tensor([[5., 6.],
        [8., 9.]])

In [ ]:
x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])

In [ ]:
x[-1::-1, -1::-1]

array([[12, 11, 10],
       [ 9,  8,  7],
       [ 6,  5,  4],
       [ 3,  2,  1]])